### PR TITLE
rewrite C# lambda function in F# fixing Issue 1514

### LINKED ISSUE #1514: Bug - there is a piece of C# code in F# template
In the F# [project template](https://github.com/Azure/azure-functions-templates/blob/39602d6a80a3b84924992cbb8baa6a2db590f54a/Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Program.fs), there is a [C# lambda function](https://github.com/Azure/azure-functions-templates/blob/39602d6a80a3b84924992cbb8baa6a2db590f54a/Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Program.fs#L10) in this F# code, making it fail to compile.

```fsharp
let host =
        HostBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureServices(services => {
                services.AddApplicationInsightsTelemetryWorkerService();
                services.ConfigureFunctionsApplicationInsights();
            })
            .Build()
```

In addition, this dot-method calling is not an F# style at all. 

Could someone familiar with both languages please fix these?

### PR DESCRIPTION
**Pull request by kumkee**
This is to fix issue https://github.com/Azure/azure-functions-templates/issues/1514

### CODE REVIEW

**Comment by kumkee** [comment]
@microsoft-github-policy-service agree [company="{kumkee}"]

**Comment by kumkee** [comment]
@microsoft-github-policy-service agree

**Review by mattchenderson — APPROVED** [review]
Hi @kumkee - thank you for catching this and for submitting this PR! Apologies for the delay in handling. The changes here look good, and we'll get this in.

I will separately ensure the right testing guard rails are in place so that an erroneous change like what led to the bad state cannot happen again.

**Pull request merged**
