### PR TITLE
Removing Queue trigger F# template

### PR DESCRIPTION
**Pull request by soninaren**

### CODE REVIEW

**Comment by davidebbo** [comment]
We really should have a 'disable' flag that we can set to make the UI ignore it without yanking everything.

But for now this will do!

**Comment by soninaren** [comment]
@alrod can you do a quick signoff on this

**Comment by mathewc** [comment]
Yes I was thinking the same thing. Logged: https://github.com/Azure/azure-webjobs-sdk-templates/issues/119

**Comment by alrod** [comment]
@soninaren, looks good

**Comment by soninaren** [comment]
:+1:

**Pull request merged**
