### PR TITLE
Removing the rowkey from table input binding.

### PR DESCRIPTION
**Pull request by soninaren**

### CODE REVIEW

**Comment by fabiocav** [comment]
This looks good. 👍

**Comment by mathewc** [comment]
There might be valid scenarios where you want to input bind to a single row, right?

The Table binding needs work and we have issue(s) tracking that. However, I believe now that the binding supports both query based bindings (returning an array) as well as a singleton?

**Comment by soninaren** [comment]
adding rowkey is not working at the moment. Have removed it temporarily. will add it back once the issue has been resolved.

https://github.com/Azure/azure-webjobs-sdk-script/issues/261

**Comment by mathewc** [comment]
Got it. I'll handle that issue with the batch of other Table binding work I'll be getting to soon.

**Pull request merged**
