### PR TITLE
Add name query template on dotnet isolated. 

### PR DESCRIPTION
**Pull request by komayama**
I added a name query the bellow template on dotnet isolated. We should be same condition template between .NET and other language.

- .NET Core
- .NET Framework

### CODE REVIEW

**Comment by liliankasem** [comment]
@komayama how have you validated and test the templates?

Edit: Also please rebase from the dev branch so we can run the pipelines on this PR

**Comment by komayama** [comment]
@liliankasem I already build (gulp)and check on local environment. And then I merged fixed change.

**Comment by liliankasem** [comment]
> @liliankasem I already build (gulp)and check on local environment. And then I merged fixed change.

Did you go through the steps in the readme to create an app using the template locally via visual studio and see if your changes were there + if you were able to build and run the function app created from this template?

**Comment by komayama** [comment]
Hi @liliankasem,

Yeah, I have tried to test on locally the bellow steps.


1. I clone azure-function-template repository and fixed template for donet-isolated (.NET core and .NET Framewwork)
.NET Core
image

.NET Framework
image


2. Build update template using by `gulp build-all` command on Build directory and see nupkg files on bin/VS directory.
image


3. Confirmed which version using `LastKnownGood-v2167102` file on `\AppData\Local\AzureFunctionsTools\Tags\v4` This is 4.90.0
image

4. I changed the bellow directory and build nupkg on bin/VS of azure-function-template repository rename and copy that Visual Studio template directory.
\AppData\Local\AzureFunctionsTools\Releases\4.90.0\net8-isolated\templates

- Microsoft.Azure.Functions.Worker.ProjectTemplates.4.0.1.nupkg -> ProjectTemplates.nupkg
- Microsoft.Azure.Functions.Worker.ProjectTemplates.4.0.1.nupkg -> ItemTemplates.nupkg

5. Create new project, HTTP trigger code from Visual Studio. I could see updated dotnet-isolated HTTP trigger template.
.NET core
image

.NET Framework
image

**Review by liliankasem — APPROVED** [review]

**Comment by liliankasem** [comment]
Validation looks good to me, thank you!

**Pull request merged**
