### PR TITLE
Add WebJobs Project template

### PR DESCRIPTION
**Pull request by christopheranderson**
Created a WebJobs template project for dotnet cli

Currently have a sample hosted here: https://www.myget.org/feed/crandycodes/package/nuget/Microsoft.Azure.WebJobs.ProjectTemplate

I might need some guidance on how to manage the NuGet package/etc. I just published to my own feed via CLI - not sure if we normally want a nuspec file or something like that.

## Testing
Two options:
1. Clone my fork and install via `dotnet new -i ./content`
2. Install via MyGet feed - `dotnet new -i "Microsoft.Azure.WebJobs.ProjectTemplate::0.1.0-dev"`

<details>
<summary>Sample NuGet.Config for accessing my MyGet</summary>
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="App Service" value="https://www.myget.org/F/azure-appservice/api/v3/index.json" protocolVersion="3" /> 
    <add key="crandycodes" value="https://www.myget.org/F/crandycodes/api/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
</details>

</br>

Once you've installed the package, just create an empty directory for your new project and type `dotnet new azure-webjobs`

This requires the latest version of dotnet core to run. You can run `dotnet --version` to see what version you're using. I developed and tested on "2.0.0-preview2-006497" on MacOS.

### CODE REVIEW

**Comment by soninaren** [comment]
Is this the right repository for webjobs project template?

**Comment by christopheranderson** [comment]
It's a good question. I chose to use this repo because I think we can actually reuse the Functions templates for WebJobs templates, as well. Just needed to add a new project type. Given the name of the repo, I think it probably makes sense. @paulbatum / @lindydonna - opinions?

**Comment by paulbatum** [comment]
So I think its a bit complicated. We expect to have branches in this repo that correspond to major versions of functions. From that perspective, putting webjobs templates here doesn't feel quite right. But maybe its not a big deal - we could say "well functions 2.x uses webjobs 3.x, so access the 2.x branch here for 3.x webjobs templates".

**Comment by soninaren** [comment]
I believe this would go in v2.x branch. Closing this one. Please re-open against v2.x branch.

**Pull request closed without merging**
