### PR TITLE
Adding defaultFunctionName to metadata.json and indentation consistent across json files

### PR DESCRIPTION
**Pull request by soninaren**
Have added defaultFunctionName to metadata.json for all templates and made indentation consistent across all json files.
use https://github.com/Azure/azure-webjobs-sdk-templates/pull/40/files?w=1 
to see just non-while space changes

### CODE REVIEW

**Comment by davidebbo** [comment]
Tip to reviewers: add `?w=1` to the review link to ignore the whitespace changes and see the true change. So https://github.com/Azure/azure-webjobs-sdk-templates/pull/40/files?w=1

**Comment by alrod** [comment]
looks good

**Comment by soninaren** [comment]
@christopheranderson if you want to take a quick look

**Comment by soninaren** [comment]
Address #37

**Pull request merged**
