### PR TITLE
Removing unnecessary namespace references

### PR DESCRIPTION
**Pull request by fabiocav**

### CODE REVIEW

**Comment by fabiocav** [comment]
***DO NOT MERGE*** this PR until https://github.com/Azure/azure-webjobs-sdk-script/pull/187 is deployed.

**Comment by davidebbo** [comment]
:shipit: (pending deployment).

**Comment by davidebbo** [comment]
@fabiocav  Deployment is complete, so feel free to merge and verify. Thanks!

**Comment by fabiocav** [comment]
@davidebbo missed the notification on this. Let me know when we're clear to merge items as it is a lot more impactful now.

**Comment by davidebbo** [comment]
I think we can still do it, but first manually check that the function runs correctly if you use current template and yank those lines.

**Comment by christopheranderson** [comment]
@fabiocav - Can you redo this PR to the dev branch?

**Comment by soninaren** [comment]
pushed to dev manually. closing this one

**Pull request closed without merging**
